Data Directory: music-library/
Songs:
- Descr: '"Positive Chill nice rhythm forward good energy summer Electronic Downtempo
    Chillout Trip hop Mellow Rhythmic Lush Atmospheric Calm Nocturnal Instrumental"'
  Energy: Low
  File: EmeraldHorizon.mp3
  Genre: Jazz
  Instrumentation:
  - Drums
  - Eletronic
  Mood:
  - Relaxing
  - Calm
  Tempo: Slow
- Descr: '"VERY MINIMAL sparse piano new age Instrumental New age Ambient Modern classical
    Western classical music Classical music Post-minimalism Calm Atmospheric Melancholic
    Ethereal"'
  Energy: Low
  File: RandomEtherealPiano.mp3
  Genre: Classical
  Instrumentation: Piano
  Mood:
  - Calm
  - Relaxing
  Tempo: Slow
- Descr: '"sound w DRAMA end ambient strings film Instrumental Ambient Strings Film
    score Cinematic classical Classical music Western classical music Melodic Orchestral
    Bittersweet Uplifting Playful"'
  Energy: Medium
  File: TheShire.mp3
  Genre: Classical
  Instrumentation: Orchestral
  Mood: Professional
  Tempo: Slow
- Descr: '"Lonesome jazzy tenor sax piano dark smokey bar Bourbon neat Instrumental
    Drums Keyboard Strings Piano Smooth jazz Jazz Jazz fusion Introspective Mellow
    Repetitive Melancholic Romantic Peaceful Melodic Atmospheric Soothing Soft"'
  Energy: Low
  File: SmoothJazz.mp3
  Genre: Jazz
  Instrumentation:
  - Piano
  - Acoustic
  - Band
  Mood:
  - Calm
  - Relaxing
  - Cool
  Tempo: Slow
- Descr: '"Bosa sax guitar rim chill relaxing Instrumental Smooth jazz Easy listening
    Lounge Jazz Calm"'
  Energy: Low
  File: SmoothLatin.mp3
  Genre: Lounge
  Instrumentation:
  - Guitar
  - Acoustic
  Mood:
  - Calm
  - Relaxing
  Tempo: Mid
- Descr: '"Instrumental SAX heavy trombone big band upbeat Swing Jazz Playful Mellow
    Acoustic"'
  Energy: Medium
  File: CafeGroove.mp3
  Genre: Jazz
  Instrumentation:
  - Orchestral
  - Acoustic
  Mood:
  - Upbeat
  - Energetic
  Tempo: Fast
- Descr: '"SNARE VERY uptempo w sax drum kit nice swingy melody pop upbeat piano section
    vaudville scene change intermission music"'
  Energy: Medium
  File: DixieSwing.mp3
  Genre: Jazz
  Instrumentation: Acoustic
  Mood:
  - Upbeat
  - Energetic
  Tempo: Fast
- Descr: '"mechanical tin piano high dixiland uptempo ragtime clarinet horn piano
    snare"'
  Energy: Medium
  File: DixieSwing2.mp3
  Genre: Jazz
  Instrumentation: Acoustic
  Mood:
  - Upbeat
  - Energetic
  Tempo: Fast
- Descr: '"Starts acoustic guitar lovely acoustic guitar sweet gentle spring lyrical
    piano line soft electric guitar contemplative whistful"'
  Energy: Low
  File: SweetGuitar.mp3
  Genre: Casual
  Instrumentation:
  - Guitar
  - Acoustic
  Mood:
  - Relaxing
  - Calm
  Tempo: Mid
- Descr: '"guitar slap start chill easy road-trip windows warm afternoon hand window
    air nice electric guitar keys trade"'
  Energy: Low
  File: SweetGuitar2.mp3
  Genre: Casual
  Instrumentation:
  - Guitar
  - Acoustic
  Mood:
  - Calm
  - Upbeat
  - Relaxing
  Tempo: Mid
- Descr: '"super-treble w beat energetic pop-techno synth FAST"'
  Energy: High
  File: ClimbingHigher1.mp3
  Genre: Dance
  Instrumentation:
  - Drums
  - Eletronic
  Mood:
  - Inspirational
  - Upbeat
  - Energetic
  Tempo: Fast
- Descr: '"easy listening energetic mellow piano drum really nice groove"'
  Energy: Medium
  File: ClimbingHigher2.mp3
  Genre: Pop
  Instrumentation:
  - Piano
  - Drums
  Mood:
  - Inspirational
  - Upbeat
  Tempo: Mid
- Descr: '"BIG right gate drama climactic anticipation time-ticking chase scene suspense
    cello strings"'
  Energy: High
  File: BigAndBold.mp3
  Genre: Rock
  Instrumentation:
  - Drums
  - Orchestral
  - Strings
  Mood:
  - Exciting
  - Energetic
  Tempo: Fast
- Descr: '"big drum heavy electric guitar synth great rhythm"'
  Energy: High
  File: BigAndBold2.mp3
  Genre: Rock
  Instrumentation:
  - Drums
  - Guitar
  - Eletronic
  Mood:
  - Exciting
  - Inspirational
  - Energetic
  Tempo: Mid
- Descr: '"Energetic dance music suitable party atmosphere exciting event product"'
  Energy: High
  File: CatWalk.mp3
  Genre: Dance
  Instrumentation:
  - Drums
  - Eletronic
  Mood:
  - Exciting
  - Upbeat
  - Energetic
  - Fun
  Tempo: Fast
- Descr: '"Electronic energetic futuristic tune mostly driving kind energy Very professional
    sounding Suitable business high tech"'
  Energy: Medium
  File: GetUpAndGo.mp3
  Genre: Dance
  Instrumentation:
  - Drums
  - Eletronic
  Mood:
  - Upbeat
  - Energetic
  - Professional
  Tempo: Fast
- Descr: '"just electronic riff then beat Pretty good tech positive energy Professional
    Good what-if possibilities imagination future"'
  Energy: Medium
  File: ThisIsTheFuture.mp3
  Genre: Electronic
  Instrumentation:
  - Drums
  - Eletronic
  Mood:
  - Professional
  - Futuristic
  - Upbeat
  Tempo: Fast
- Descr: '"Feminine energy happy family festivals contests"'
  Energy: High
  File: SummerParty.mp3
  Genre: Casual
  Instrumentation:
  - Drums
  - Piano
  Mood:
  - Fun
  - Upbeat
  - Energetic
  - Professional
  Tempo: Fast
- Descr: '"Jazz random style Very smooth cool Not super melodic"'
  Energy: Low
  File: HonkyTonky.mp3
  Genre: Jazz
  Instrumentation:
  - Guitar
  - Drums
  Mood:
  - Calm
  - Relaxing
  - Professional
  - Upbeat
  Tempo: Mid
- Descr: '"Very commercial sound kind music many exciting new products/possibilities
    people"'
  Energy: Medium
  File: TogetherWeCan.mp3
  Genre: Casual
  Instrumentation: Band
  Mood:
  - Fun
  - Energetic
  - Upbeat
  - Professional
  Tempo: Fast
- Descr: '"Dramatic strings music kind normally diamond commericials momentous grand
    Posh people powerful people rich famous"'
  Energy: High
  File: TheRoyals.mp3
  Genre: Classical
  Instrumentation:
  - Acoustic
  - Drums
  Mood:
  - Inspirational
  - Energetic
  - Professional
  Tempo: Mid
- Descr: '"Sounds music memoire telling sweet story love tenderness longing wistfulness
    tenderness innocense"'
  Energy: Low
  File: IWroteYouALetter.mp3
  Genre: Classical
  Instrumentation: Piano
  Mood:
  - Calm
  - Relaxing
  - Professional
  Tempo: Slow
- Descr: '"little melancholy warm calm slight air sadness Music someone memorium Could
    also elegance"'
  Energy: Low
  File: AllTheBeautifulThings.mp3
  Genre: Classical
  Instrumentation: Piano
  Mood:
  - Calm
  - Melancholic
  - Relaxing
  Tempo: Slow
- Descr: '"Elegant energetic music banquet wedding something people"'
  Energy: High
  File: FancyParty.mp3
  Genre: Classical
  Instrumentation: Strings
  Mood:
  - Inspirational
  - Upbeat
  - Energetic
  Tempo: Mid
- Descr: '"Folksy casual Music footage road trip sort outdoor activity maybe bar scene
    summer nights summer afternoons"'
  Energy: Medium
  File: TruckStop.mp3
  Genre: Country
  Instrumentation:
  - Guitar
  - Drums
  Mood:
  - Upbeat
  - Cool
  - Professional
  Tempo: Mid
- Descr: '"like music movie danger adventure explosions high drama something very
    scary dangerous warnings dramatic way"'
  Energy: High
  File: HighDrama.mp3
  Genre: Cinematic
  Instrumentation:
  - Strings
  - Orchestral
  Mood:
  - Dramatic
  - Exciting
  Tempo: Fast
- Descr: '"inspirational vibe possibilities Success possible Hard work pays mission
    people together Community fellowship family Inclusiveness"'
  Energy: Medium
  File: Possibilities.mp3
  Genre: Classical
  Instrumentation:
  - Piano
  - Strings
  - Orchestral
  Mood:
  - Upbeat
  - Inspirational
  - Professional
  Tempo: Mid
- Descr: '"music spa dream relaxation also about space underwater exploration Anything
    slow kind feeling"'
  Energy: Low
  File: DreamScape.mp3
  Genre: Ethereal
  Instrumentation: Eletronic
  Mood:
  - Calm
  - Inspirational
  Tempo: Slow
- Descr: '"Casual cool jazz vibe piano man fun Very professional sounding also quite
    energetic"'
  Energy: Medium
  File: JazzyNightOut.mp3
  Genre: Jazz
  Instrumentation: Acoustic
  Mood:
  - Cool
  - Upbeat
  - Professional
  Tempo: Mid
- Descr: '"very ethereal Almost woo-woo sounding Space meditation dreams imagination
    relaxation holistic Religious perhaps"'
  Energy: Low
  File: DreamScape2.mp3
  Genre: Ethereal
  Instrumentation: Eletronic
  Mood:
  - Calm
  - Relaxing
  Tempo: Slow
- Descr: '"Very commercial certain longing not quite sad little wistful soft suitable
    emotional tender mood"'
  Energy: Low
  File: AlwaysRemember.mp3
  Genre: Ambient
  Instrumentation:
  - Piano
  - Acoustic
  Mood:
  - Calm
  - Melancholic
  - Professional
  Tempo: Mid
- Descr: '"sounding Emotionally neutral Perhaps slightly serious side Classy Professional"'
  Energy: Low
  File: Succession.mp3
  Genre: Classical
  Instrumentation: Piano
  Mood:
  - Calm
  - Professional
  Tempo: Fast
- Descr: '"almost european old world sound Maybe greek footage beach vacation trip
    abroad"'
  Energy: Medium
  File: Technicolor.mp3
  Genre: Folk
  Instrumentation: Band
  Mood:
  - Upbeat
  - Fun
  Tempo: Mid
- Descr: '"something scene Bladerunner sort futuristic tech innovation vibe specifications
    new product Prototypes very professional sound"'
  Energy: Medium
  File: ThisChangesEverything.mp3
  Genre: Ethereal
  Instrumentation:
  - Drums
  - Eletronic
  Mood:
  - Futuristic
  - Calm
  - Professional
  Tempo: Mid
- Descr: '"music video game Mario other fast paced game character quickly obstacles
    enemies energetic playful definitely video-gamy"'
  Energy: High
  File: MarioKart.mp3
  Genre: Electronic
  Instrumentation:
  - Drums
  - Eletronic
  Mood:
  - Exciting
  - Futuristic
  - Energetic
  - Fun
  Tempo: Fast
- Descr: '"Very commercial Professional beat calmer finish"'
  Energy: Medium
  File: ThisIsIt.mp3
  Genre: Dance
  Instrumentation:
  - Drums
  - Eletronic
  Mood:
  - Upbeat
  - Inspirational
  - Professional
  Tempo: Fast
- Descr: '"Noisy harsh high energy beat Video game sound"'
  Energy: High
  File: FastAndHard.mp3
  Genre: Dance
  Instrumentation: Eletronic
  Mood:
  - Exciting
  - Energetic
  - Fun
  Tempo: Fast
- Descr: '"Very energetic Sporty Lots action Fast scenes Excitement"'
  Energy: High
  File: Relentless.mp3
  Genre: Dance
  Instrumentation:
  - Drums
  - Eletronic
  Mood:
  - Exciting
  - Energetic
  - Fun
  Tempo: Fast
- Descr: '"Lovely moment Mindfulness Everything ok"'
  Energy: Low
  File: CalmingSpirit.mp3
  Genre: Ethereal
  Instrumentation: Eletronic
  Mood:
  - Calm
  - Relaxing
  - Professional
  Tempo: Slow
- Descr: '"Very high energy also quite professional Night time club scene baller life
    exotic destinations fancy cars Beautiful people"'
  Energy: High
  File: TakeItAllIn.mp3
  Genre: Electronic
  Instrumentation:
  - Eletronic
  - Drums
  Mood:
  - Energetic
  - Exciting
  - Dramatic
  Tempo: Mid
- Descr: '"Inspirational uplifting story hard work success Never together Anything
    possible just hard"'
  Energy: High
  File: AsGoodAsItGets.mp3
  Genre: Electronic
  Instrumentation: Eletronic
  Mood:
  - Upbeat
  - Energetic
  - Inspirational
  Tempo: Mid
- Descr: '"Very energetic video games youthful Girls dressup Party party party Barbie
    Amusement parks very fun happy tune energy"'
  Energy: High
  File: DanceDanceDance.mp3
  Genre: Dance
  Instrumentation:
  - Drums
  - Eletronic
  Mood:
  - Fun
  - Upbeat
  - Professional
  Tempo: Fast
- Descr: '"Very techy futuristic professional"'
  Energy: Medium
  File: EuroChique.mp3
  Genre: Dance
  Instrumentation:
  - Drums
  - Eletronic
  Mood:
  - Upbeat
  - Fun
  - Professional
  Tempo: Mid
- Descr: '"Sounds very commerical jingle happy vibe Evokes crowds groups good wholesome
    time"'
  Energy: Medium
  File: TimeOfOurLives.mp3
  Genre: Rock
  Instrumentation:
  - Drums
  - Band
  Mood:
  - Upbeat
  - Fun
  - Professional
  Tempo: Fast
- Descr: '"Sounds soundtrack Japanese Anime Kind epic battle vibe music several movements
    explosive epic feel Very fast tempo Adventure action"'
  Energy: High
  File: RockAnthem.mp3
  Genre: Rock
  Instrumentation:
  - Band
  - Guitar
  - Drums
  Mood:
  - Energetic
  - Dramatic
  Tempo: Fast
- Descr: '"ridiculously fast-paced Extremely energetic"'
  Energy: High
  File: HurryUpAndHitIt.mp3
  Genre: Electronic
  Instrumentation:
  - Drums
  - Eletronic
  Mood:
  - Exciting
  - Energetic
  - Fun
  Tempo: Fast
- Descr: '"Commercial bit country vibe Could almost anything casual positive vibe"'
  Energy: Medium
  File: WhatEveryoneWants.mp3
  Genre: Casual
  Instrumentation:
  - Guitar
  - Drums
  - Band
  Mood:
  - Upbeat
  - Professional
  Tempo: Mid
- Descr: '"Serious techy futuristic energy beat music little repetitive good background
    something professional technical"'
  Energy: Medium
  File: ListenToTheFuture.mp3
  Genre: Electronic
  Instrumentation:
  - Drums
  - Eletronic
  Mood:
  - Futuristic
  - Energetic
  - Professional
  Tempo: Fast
- Descr: '"Futuristic not too far there High energy Positive vibe not quite festive
    ambitious Business night life"'
  Energy: Medium
  File: InMotion.mp3
  Genre: Dance
  Instrumentation:
  - Drums
  - Eletronic
  Mood:
  - Energetic
  - Professional
  Tempo: Fast
- Descr: '"very Greek sound Definitely old world vibe Only really appropriate things
    mediterranean old world charm"'
  Energy: Medium
  File: TackyOldTimey.mp3
  Genre: Folk
  Instrumentation:
  - Band
  - Strings
  Mood:
  - Upbeat
  - Fun
  Tempo: Mid
- Descr: '"Professional commercial good almost anything good positive energy"'
  Energy: Medium
  File: CheckTheseOut.mp3
  Genre: Pop
  Instrumentation: Eletronic
  Mood:
  - Energetic
  - Futuristic
  - Professional
  Tempo: Mid
- Descr: '"Very dreamy ethereal space relaxing sleeping dreaming"'
  Energy: Low
  File: PeacefulSurrender.mp3
  Genre: Ethereal
  Instrumentation: Eletronic
  Mood:
  - Calm
  - Relaxing
  - Professional
  Tempo: Slow
