Data Directory: music-library/
Songs:
- Descr: "Positive, chill with a nice rhythm. Ideal for summer vibes and mellow moods. Atmospheric and calm, but not very remarkable."
  Energy: Low
  File: EmeraldHorizon.mp3
  Genre: Jazz
  Instrumentation:
  - Drums
  - Electronic
  Mood:
  - Relaxing
  - Calm
  Tempo: Slow
- Descr: "Minimalist piano, new age, and ambient with a melancholic and ethereal feel."
  Energy: Low
  File: RandomEtherealPiano.mp3
  Genre: Classical
  Instrumentation: Piano
  Mood:
  - Calm
  - Relaxing
  Tempo: Slow
- Descr: "Dramatic ambient strings, cinematic and bittersweet. Uplifting and playful."
  Energy: Medium
  File: TheShire.mp3
  Genre: Classical
  Instrumentation: Orchestral
  Mood: Professional
  Tempo: Slow
- Descr: "Lonesome jazz with a smoky, dark vibe. Ideal for night or romantic themes."
  Energy: Low
  File: SmoothJazz.mp3
  Genre: Jazz
  Instrumentation:
  - Piano
  - Acoustic
  - Band
  Mood:
  - Calm
  - Relaxing
  - Cool
  Tempo: Slow
- Descr: "Bossa nova with sax and guitar, relaxing but not for general use."
  Energy: Low
  File: SmoothLatin.mp3
  Genre: Lounge
  Instrumentation:
  - Guitar
  - Acoustic
  Mood:
  - Calm
  - Relaxing
  Tempo: Mid
- Descr: "Upbeat swing jazz with heavy sax and trombone. Playfully energetic."
  Energy: Medium
  File: CafeGroove.mp3
  Genre: Jazz
  Instrumentation:
  - Orchestral
  - Acoustic
  Mood:
  - Upbeat
  - Energetic
  Tempo: Fast
- Descr: "Uptempo swing with sax and drums. Adds a humorous touch."
  Energy: Medium
  File: DixieSwing.mp3
  Genre: Jazz
  Instrumentation: Acoustic
  Mood:
  - Upbeat
  - Energetic
  Tempo: Fast
- Descr: "Ragtime with a mechanical, tinny sound. Choose for an innocent, upbeat feel."
  Energy: Medium
  File: DixieSwing2.mp3
  Genre: Jazz
  Instrumentation: Acoustic
  Mood:
  - Upbeat
  - Energetic
  Tempo: Fast
- Descr: "Gentle acoustic guitar with a contemplative, wistful feel."
  Energy: Low
  File: SweetGuitar.mp3
  Genre: Casual
  Instrumentation:
  - Guitar
  - Acoustic
  Mood:
  - Relaxing
  - Calm
  Tempo: Mid
- Descr: "Chill road-trip vibe with a warm, easy-going sound. Professional and soft."
  Energy: Low
  File: SweetGuitar2.mp3
  Genre: Casual
  Instrumentation:
  - Guitar
  - Acoustic
  Mood:
  - Calm
  - Upbeat
  - Relaxing
  Tempo: Mid
- Descr: "Energetic pop-techno with a fast, driving beat. Great for high-energy themes."
  Energy: High
  File: ClimbingHigher1.mp3
  Genre: Dance
  Instrumentation:
  - Drums
  - Electronic
  Mood:
  - Inspirational
  - Upbeat
  - Energetic
  Tempo: Fast
- Descr: "Mellow piano and drums with a nice groove. Slightly generic."
  Energy: Medium
  File: ClimbingHigher2.mp3
  Genre: Pop
  Instrumentation:
  - Piano
  - Drums
  Mood:
  - Inspirational
  - Upbeat
  Tempo: Mid
- Descr: "Dramatic orchestral with a climactic, suspenseful feel. Great for intense scenes."
  Energy: High
  File: BigAndBold.mp3
  Genre: Rock
  Instrumentation:
  - Drums
  - Orchestral
  - Strings
  Mood:
  - Exciting
  - Energetic
  Tempo: Fast
- Descr: "Heavy drum and guitar with a serious, dramatic vibe."
  Energy: High
  File: BigAndBold2.mp3
  Genre: Rock
  Instrumentation:
  - Drums
  - Guitar
  - Electronic
  Mood:
  - Exciting
  - Inspirational
  - Energetic
  Tempo: Mid
- Descr: "Energetic dance music for party atmospheres."
  Energy: High
  File: CatWalk.mp3
  Genre: Dance
  Instrumentation:
  - Drums
  - Electronic
  Mood:
  - Exciting
  - Upbeat
  - Energetic
  - Fun
  Tempo: Fast
- Descr: "Futuristic and energetic with a professional sound. Suitable for business."
  Energy: Medium
  File: GetUpAndGo.mp3
  Genre: Dance
  Instrumentation:
  - Drums
  - Electronic
  Mood:
  - Upbeat
  - Energetic
  - Professional
  Tempo: Fast
- Descr: "Electronic riff with a techy, futuristic vibe. Positive and professional."
  Energy: Medium
  File: ThisIsTheFuture.mp3
  Genre: Electronic
  Instrumentation:
  - Drums
  - Electronic
  Mood:
  - Professional
  - Futuristic
  - Upbeat
  Tempo: Fast
- Descr: "Happy, feminine energy. Great for family and festive scenes."
  Energy: High
  File: SummerParty.mp3
  Genre: Casual
  Instrumentation:
  - Drums
  - Piano
  Mood:
  - Fun
  - Upbeat
  - Energetic
  - Professional
  Tempo: Fast
- Descr: "Smooth, jazzy, and eclectic. Choose for very jazzy themes."
  Energy: Low
  File: HonkyTonky.mp3
  Genre: Jazz
  Instrumentation:
  - Guitar
  - Drums
  Mood:
  - Calm
  - Relaxing
  - Professional
  - Upbeat
  Tempo: Mid
- Descr: "Commercial sound for exciting, new products. Energetic and uplifting."
  Energy: Medium
  File: TogetherWeCan.mp3
  Genre: Casual
  Instrumentation: Band
  Mood:
  - Fun
  - Energetic
  - Upbeat
  - Professional
  Tempo: Fast
- Descr: "Dramatic strings for grand, powerful scenes. Ideal for luxury or impactful moments."
  Energy: High
  File: TheRoyals.mp3
  Genre: Classical
  Instrumentation:
  - Acoustic
  - Drums
  Mood:
  - Inspirational
  - Energetic
  - Professional
  Tempo: Mid
- Descr: "Sweet and tender music, ideal for storytelling and wistful moments."
  Energy: Low
  File: IWroteYouALetter.mp3
  Genre: Classical
  Instrumentation: Piano
  Mood:
  - Calm
  - Relaxing
  - Professional
  Tempo: Slow
- Descr: "Warm, calm, slightly melancholic with fond memories. Elegant and serene."
  Energy: Low
  File: AllTheBeautifulThings.mp3
  Genre: Classical
  Instrumentation: Piano
  Mood:
  - Calm
  - Melancholic
  - Relaxing
  Tempo: Slow
- Descr: "Elegant, energetic music for fancy events like weddings or banquets."
  Energy: High
  File: FancyParty.mp3
  Genre: Classical
  Instrumentation: Strings
  Mood:
  - Inspirational
  - Upbeat
  - Energetic
  Tempo: Mid
- Descr: "Folksy, casual music for road trips or outdoor activities. Perfect for summer scenes."
  Energy: Medium
  File: TruckStop.mp3
  Genre: Country
  Instrumentation:
  - Guitar
  - Drums
  Mood:
  - Upbeat
  - Cool
  - Professional
  Tempo: Mid
- Descr: "High drama with explosive, adventurous energy. Intense and suspenseful."
  Energy: High
  File: HighDrama.mp3
  Genre: Cinematic
  Instrumentation:
  - Strings
  - Orchestral
  Mood:
  - Dramatic
  - Exciting
  Tempo: Fast
- Descr: "Inspirational with a focus on success, hard work, and community. Uplifting and motivational."
  Energy: Medium
  File: Possibilities.mp3
  Genre: Classical
  Instrumentation:
  - Piano
  - Strings
  - Orchestral
  Mood:
  - Upbeat
  - Inspirational
  - Professional
  Tempo: Mid
- Descr: "Dreamy, spa-like relaxation with a sense of space and exploration."
  Energy: Low
  File: DreamScape.mp3
  Genre: Ethereal
  Instrumentation: Electronic
  Mood:
  - Calm
  - Inspirational
  Tempo: Slow
- Descr: "Cool jazz vibe, professional and fun. Great for energetic, lively scenes."
  Energy: Medium
  File: JazzyNightOut.mp3
  Genre: Jazz
  Instrumentation: Acoustic
  Mood:
  - Cool
  - Upbeat
  - Professional
  Tempo: Mid
- Descr: "Ethereal, meditative, and slightly mystical. Suitable for relaxation and imagination."
  Energy: Low
  File: DreamScape2.mp3
  Genre: Ethereal
  Instrumentation: Electronic
  Mood:
  - Calm
  - Relaxing
  Tempo: Slow
- Descr: "Wistful and tender, with a commercial vibe. Soft and emotional."
  Energy: Low
  File: AlwaysRemember.mp3
  Genre: Ambient
  Instrumentation:
  - Piano
  - Acoustic
  Mood:
  - Calm
  - Melancholic
  - Professional
  Tempo: Mid
- Descr: "Neutral and slightly serious, classy and professional."
  Energy: Low
  File: Succession.mp3
  Genre: Classical
  Instrumentation: Piano
  Mood:
  - Calm
  - Professional
  Tempo: Fast
- Descr: "European, old-world sound. Ideal for travel or vacation scenes."
  Energy: Medium
  File: Technicolor.mp3
  Genre: Folk
  Instrumentation: Band
  Mood:
  - Upbeat
  - Fun
  Tempo: Mid
- Descr: "Futuristic and professional with a quiet, techy vibe. Great for innovation or new products."
  Energy: Medium
  File: ThisChangesEverything.mp3
  Genre: Ethereal
  Instrumentation:
  - Drums
  - Electronic
  Mood:
  - Futuristic
  - Calm
  - Professional
  Tempo: Mid
- Descr: "Fast-paced, energetic music with a video game feel. Playful and exciting."
  Energy: High
  File: MarioKart.mp3
  Genre: Electronic
  Instrumentation:
  - Drums
  - Electronic
  Mood:
  - Exciting
  - Futuristic
  - Energetic
  - Fun
  Tempo: Fast
- Descr: "Commercial, professional beat with a calm ending. Great for slogans."
  Energy: Medium
  File: ThisIsIt.mp3
  Genre: Dance
  Instrumentation:
  - Drums
  - Electronic
  Mood:
  - Upbeat
  - Inspirational
  - Professional
  Tempo: Fast
- Descr: "Harsh, high-energy beat for intense, impactful themes."
  Energy: High
  File: FastAndHard.mp3
  Genre: Dance
  Instrumentation: Electronic
  Mood:
  - Exciting
  - Energetic
  - Fun
  Tempo: Fast
- Descr: "High-energy, sporty music for fast, exciting scenes."
  Energy: High
  File: Relentless.mp3
  Genre: Dance
  Instrumentation:
  - Drums
  - Electronic
  Mood:
  - Exciting
  - Energetic
  - Fun
  Tempo: Fast
- Descr: "Reassuring and encouraging, with a calming, mindful vibe."
  Energy: Low
  File: CalmingSpirit.mp3
  Genre: Ethereal
  Instrumentation: Electronic
  Mood:
  - Calm
  - Relaxing
  - Professional
  Tempo: Slow
- Descr: "High-energy, professional vibe for nightlife, luxury, and excitement."
  Energy: High
  File: TakeItAllIn.mp3
  Genre: Electronic
  Instrumentation:
  - Electronic
  - Drums
  Mood:
  - Energetic
  - Exciting
  - Dramatic
  Tempo: Mid
- Descr: "Inspirational, uplifting story with a build-up from soft to powerful. Motivates taking chances."
  Energy: High
  File: AsGoodAsItGets.mp3
  Genre: Electronic
  Instrumentation: Electronic
  Mood:
  - Upbeat
  - Energetic
  - Inspirational
  Tempo: Mid
- Descr: "Fun, energetic tune for youthful, playful scenes. Great for parties and amusement."
  Energy: High
  File: DanceDanceDance.mp3
  Genre: Dance
  Instrumentation:
  - Drums
  - Electronic
  Mood:
  - Fun
  - Upbeat
  - Professional
  Tempo: Fast
- Descr: "Techy, futuristic, and professional. Suitable for commercial purposes."
  Energy: Medium
  File: EuroChique.mp3
  Genre: Dance
  Instrumentation:
  - Drums
  - Electronic
  Mood:
  - Upbeat
  - Fun
  - Professional
  Tempo: Mid
- Descr: "Commercial, happy vibe with a group-friendly, wholesome feel."
  Energy: Medium
  File: TimeOfOurLives.mp3
  Genre: Rock
  Instrumentation:
  - Drums
  - Band
  Mood:
  - Upbeat
  - Fun
  - Professional
  Tempo: Fast
- Descr: "Epic, battle-like music with fast tempo and multiple movements. Ideal for action."
  Energy: High
  File: RockAnthem.mp3
  Genre: Rock
  Instrumentation:
  - Band
  - Guitar
  - Drums
  Mood:
  - Energetic
  - Dramatic
  Tempo: Fast
- Descr: "Extremely fast-paced and extremely energetic."
  Energy: High
  File: HurryUpAndHitIt.mp3
  Genre: Electronic
  Instrumentation:
  - Drums
  - Electronic
  Mood:
  - Exciting
  - Energetic
  - Fun
  Tempo: Fast
- Descr: "Casual, positive vibe with a bit of country influence. Versatile and easygoing."
  Energy: Medium
  File: WhatEveryoneWants.mp3
  Genre: Casual
  Instrumentation:
  - Guitar
  - Drums
  - Band
  Mood:
  - Upbeat
  - Professional
  Tempo: Mid
- Descr: "Techy, futuristic energy with a professional tone. Good for background or technical themes."
  Energy: Medium
  File: ListenToTheFuture.mp3
  Genre: Electronic
  Instrumentation:
  - Drums
  - Electronic
  Mood:
  - Futuristic
  - Energetic
  - Professional
  Tempo: Fast
- Descr: "Futuristic, high-energy with a positive, ambitious vibe. Great for business."
  Energy: Medium
  File: InMotion.mp3
  Genre: Dance
  Instrumentation:
  - Drums
  - Electronic
  Mood:
  - Energetic
  - Professional
  Tempo: Fast
- Descr: "Greek, old-world sound with Mediterranean charm."
  Energy: Medium
  File: TackyOldTimey.mp3
  Genre: Folk
  Instrumentation:
  - Band
  - Strings
  Mood:
  - Upbeat
  - Fun
  Tempo: Mid
- Descr: "Professional, commercial sound with positive energy. High quality."
  Energy: Medium
  File: CheckTheseOut.mp3
  Genre: Pop
  Instrumentation: Electronic
  Mood:
  - Energetic
  - Futuristic
  - Professional
  Tempo: Mid
- Descr: "Dreamy, ethereal music for relaxation or sleep."
  Energy: Low
  File: PeacefulSurrender.mp3
  Genre: Ethereal
  Instrumentation: Electronic
  Mood:
  - Calm
  - Relaxing
  - Professional
  Tempo: Slow
